export const INJECTION_TOKEN = {
  CLOUDINARY_CONFIG: "CLOUDINARY_CONFIG",
  GOOGLE_CONFIG: "GOOGLE_CONFIG",
} as const;

export const CLOUDINARY_CONFIG = {
  UPLOAD_PRESETS: {
    AVATAR: "pinpin_avatars",
  },
  FOLDER_NAME: {
    AVATAR: "Avatar",
  },
} as const;

export const ORIGINAL_GOOGLE_MAPS_PLACE = {
  PRICE_LEVEL: {
    PRICE_LEVEL_UNSPECIFIED: "PRICE_LEVEL_UNSPECIFIED",
    PRICE_LEVEL_FREE: "PRICE_LEVEL_FREE",
    PRICE_LEVEL_INEXPENSIVE: "PRICE_LEVEL_INEXPENSIVE",
    PRICE_LEVEL_MODERATE: "PRICE_LEVEL_MODERATE",
    PRICE_LEVEL_EXPENSIVE: "PRICE_LEVEL_EXPENSIVE",
    PRICE_LEVEL_VERY_EXPENSIVE: "PRICE_LEVEL_VERY_EXPENSIVE",
  },
  BUSINESS_STATUS: {
    BUSINESS_STATUS_UNSPECIFIED: "BUSINESS_STATUS_UNSPECIFIED",
    OPERATIONAL: "OPERATIONAL",
    CLOSED_TEMPORARILY: "CLOSED_TEMPORARILY",
    CLOSED_PERMANENTLY: "CLOSED_PERMANENTLY",
  },
} as const;

export const GOOGLE_API_URL = {
  TEXT_SEARCH: "https://places.googleapis.com/v1/places:searchText",
};
