import {
  GOOGLE_MAPS_PLACE_BUSINESS_STATUS,
  GOOGLE_MAPS_PLACE_PRICE_LEVEL,
  GoogleMapsPlaceBusinessStatus,
  GoogleMapsPlacePriceLevel,
} from "pinpin_library";
import { ORIGINAL_GOOGLE_MAPS_PLACE } from "../constants/constants.js";
import { ConstObjectValues } from "../utils/type.util.js";

function googleBusinessStatusMapper(businessStatus?: string | null): GoogleMapsPlaceBusinessStatus {
  switch (businessStatus) {
    case ORIGINAL_GOOGLE_MAPS_PLACE.BUSINESS_STATUS.OPERATIONAL:
      return GOOGLE_MAPS_PLACE_BUSINESS_STATUS.OPEN;
    case ORIGINAL_GOOGLE_MAPS_PLACE.BUSINESS_STATUS.CLOSED_TEMPORARILY:
      return GOOGLE_MAPS_PLACE_BUSINESS_STATUS.CLOSE;
    case ORIGINAL_GOOGLE_MAPS_PLACE.BUSINESS_STATUS.CLOSED_PERMANENTLY:
      return GOOGLE_MAPS_PLACE_BUSINESS_STATUS.CLOSE;
    default:
      return GOOGLE_MAPS_PLACE_BUSINESS_STATUS.UNKNOWN;
  }
}

function reverseBusinessStatusMapper(
  businessStatus: GoogleMapsPlaceBusinessStatus,
): ConstObjectValues<typeof ORIGINAL_GOOGLE_MAPS_PLACE.BUSINESS_STATUS> {
  switch (businessStatus) {
    case GOOGLE_MAPS_PLACE_BUSINESS_STATUS.OPEN:
      return ORIGINAL_GOOGLE_MAPS_PLACE.BUSINESS_STATUS.OPERATIONAL;
    case GOOGLE_MAPS_PLACE_BUSINESS_STATUS.CLOSE:
      return ORIGINAL_GOOGLE_MAPS_PLACE.BUSINESS_STATUS.CLOSED_PERMANENTLY;
    case GOOGLE_MAPS_PLACE_BUSINESS_STATUS.UNKNOWN:
    default:
      return ORIGINAL_GOOGLE_MAPS_PLACE.BUSINESS_STATUS.BUSINESS_STATUS_UNSPECIFIED;
  }
}

function googlePriceLevelMapper(pliceLevel?: string | null): GoogleMapsPlacePriceLevel {
  switch (pliceLevel) {
    case ORIGINAL_GOOGLE_MAPS_PLACE.PRICE_LEVEL.PRICE_LEVEL_UNSPECIFIED:
      return GOOGLE_MAPS_PLACE_PRICE_LEVEL.UNKNOWN;
    case ORIGINAL_GOOGLE_MAPS_PLACE.PRICE_LEVEL.PRICE_LEVEL_FREE:
      return GOOGLE_MAPS_PLACE_PRICE_LEVEL.INEXPENSIVE;
    case ORIGINAL_GOOGLE_MAPS_PLACE.PRICE_LEVEL.PRICE_LEVEL_INEXPENSIVE:
      return GOOGLE_MAPS_PLACE_PRICE_LEVEL.INEXPENSIVE;
    case ORIGINAL_GOOGLE_MAPS_PLACE.PRICE_LEVEL.PRICE_LEVEL_MODERATE:
      return GOOGLE_MAPS_PLACE_PRICE_LEVEL.MODERATE;
    case ORIGINAL_GOOGLE_MAPS_PLACE.PRICE_LEVEL.PRICE_LEVEL_EXPENSIVE:
      return GOOGLE_MAPS_PLACE_PRICE_LEVEL.EXPENSIVE;
    case ORIGINAL_GOOGLE_MAPS_PLACE.PRICE_LEVEL.PRICE_LEVEL_VERY_EXPENSIVE:
      return GOOGLE_MAPS_PLACE_PRICE_LEVEL.VERY_EXPENSIVE;
    default:
      return GOOGLE_MAPS_PLACE_PRICE_LEVEL.UNKNOWN;
  }
}

function reversePriceLevelMapper(priceLevel: GoogleMapsPlacePriceLevel): ConstObjectValues<typeof ORIGINAL_GOOGLE_MAPS_PLACE.PRICE_LEVEL> {
  switch (priceLevel) {
    case GOOGLE_MAPS_PLACE_PRICE_LEVEL.UNKNOWN:
      return ORIGINAL_GOOGLE_MAPS_PLACE.PRICE_LEVEL.PRICE_LEVEL_UNSPECIFIED;
    case GOOGLE_MAPS_PLACE_PRICE_LEVEL.INEXPENSIVE:
      return ORIGINAL_GOOGLE_MAPS_PLACE.PRICE_LEVEL.PRICE_LEVEL_INEXPENSIVE;
    case GOOGLE_MAPS_PLACE_PRICE_LEVEL.MODERATE:
      return ORIGINAL_GOOGLE_MAPS_PLACE.PRICE_LEVEL.PRICE_LEVEL_MODERATE;
    case GOOGLE_MAPS_PLACE_PRICE_LEVEL.EXPENSIVE:
      return ORIGINAL_GOOGLE_MAPS_PLACE.PRICE_LEVEL.PRICE_LEVEL_EXPENSIVE;
    case GOOGLE_MAPS_PLACE_PRICE_LEVEL.VERY_EXPENSIVE:
      return ORIGINAL_GOOGLE_MAPS_PLACE.PRICE_LEVEL.PRICE_LEVEL_VERY_EXPENSIVE;
    default:
      return ORIGINAL_GOOGLE_MAPS_PLACE.PRICE_LEVEL.PRICE_LEVEL_UNSPECIFIED;
  }
}

export { googleBusinessStatusMapper, googlePriceLevelMapper, reverseBusinessStatusMapper, reversePriceLevelMapper };
